// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cgmnlpyetcwwxzorlhyt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNnbW5scHlldGN3d3h6b3JsaHl0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcyNzc3MzYsImV4cCI6MjA3Mjg1MzczNn0.4r-usrn9KHosrFEp6DJDFJSNkI5VGJ1iUBM28VUeAyA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});